# Generated by Django 6.0.8 on 2026-08-07 17:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ERP', '0007_company_legal_form'),
        ('Fields', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CadastralParcel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('capakey', models.CharField(blank=True, help_text='Identifiant cadastral unique (ex: BE)', max_length=100)),
                ('name', models.CharField(max_length=255)),
                ('surface', models.FloatField(blank=True, null=True)),
                ('official_surface', models.FloatField(blank=True, null=True)),
                ('geojson_data', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ERP.company')),
            ],
        ),
        migrations.DeleteModel(
            name='Plot',
        ),
    ]
