services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/workspace
    ports:
      - "8000:8000"
      # --- AJOUTEZ CES DEUX LIGNES ---
    command: sleep infinity
    tty: true
    # -------------------------------
    environment:
      - DATABASE_URL=postgres://agricore_user:agricore_pass@agricore-db:5432/agricore_db
      - DEBUG=1
    depends_on:
      - agricore-db

  agricore-db:
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: agricore_db
      POSTGRES_USER: agricore_user
      POSTGRES_PASSWORD: agricore_pass
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: