# Generated by Django 6.0 on 2026-05-28 16:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="BusinessPartner",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        blank=True, choices=[("MR", "Mr"), ("MME", "Mme")], max_length=5
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("first_name", models.CharField(blank=True, max_length=64)),
                ("email", models.EmailField(blank=True, max_length=255)),
                ("phone", models.CharField(blank=True, max_length=30)),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("CUS", "Customer"),
                            ("SUP", "Supplier"),
                            ("CON", "Contact"),
                            ("GEN", "General"),
                        ],
                        default="CUS",
                        max_length=3,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name="Company",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("vat_number", models.CharField(blank=True, max_length=32, null=True)),
                ("street", models.CharField(blank=True, max_length=255)),
                ("number", models.CharField(blank=True, max_length=20)),
                ("postal_code", models.CharField(blank=True, max_length=20)),
                ("city", models.CharField(blank=True, max_length=100)),
                (
                    "country",
                    models.CharField(
                        choices=[
                            ("be", "Belgium"),
                            ("fr", "France"),
                            ("nl", "Netherlands"),
                            ("de", "Germany"),
                        ]
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Customer",
            fields=[
                (
                    "businesspartner_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="ERP.businesspartner",
                    ),
                ),
                ("vat_number", models.CharField(blank=True, max_length=32)),
            ],
            bases=("ERP.businesspartner",),
        ),
        migrations.AddField(
            model_name="businesspartner",
            name="company",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="partners",
                to="ERP.company",
            ),
        ),
        migrations.CreateModel(
            name="CompanyAccess",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("OW", "Owner"),
                            ("EM", "Employee"),
                            ("AC", "Accountant"),
                        ],
                        default="OW",
                        max_length=4,
                    ),
                ),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_permissions",
                        to="ERP.company",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="company_permissions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "unique_together": {("user", "company")},
            },
        ),
        migrations.AddField(
            model_name="company",
            name="users",
            field=models.ManyToManyField(
                related_name="companies",
                through="ERP.CompanyAccess",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=64)),
                ("description", models.TextField(max_length=250)),
                (
                    "unit_measure",
                    models.CharField(
                        choices=[
                            ("kg", "Kg"),
                            ("l", "L"),
                            ("t", "Ton"),
                            ("u", "Unit"),
                            ("h", "Hour"),
                            ("a", "Are"),
                            ("ha", "Hectare"),
                        ],
                        max_length=3,
                    ),
                ),
                ("unit_price", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "type",
                    models.CharField(
                        choices=[("o", "Object"), ("s", "Service")],
                        default="o",
                        max_length=3,
                    ),
                ),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="products",
                        to="ERP.company",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Transaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("creation_date", models.DateTimeField(auto_now_add=True)),
                (
                    "total_net",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "total_vat",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "total_gross",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[("sale", "Sale"), ("purchase", "Purchase")],
                        default="sale",
                        max_length=8,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("new", "New"),
                            ("progress", "In Progress"),
                            ("cancelled", "Cancelled"),
                            ("completed", "Completed"),
                        ],
                        default="new",
                        max_length=20,
                    ),
                ),
                (
                    "local_sequence",
                    models.PositiveIntegerField(blank=True, editable=False, null=True),
                ),
                (
                    "public_id",
                    models.CharField(
                        blank=True, editable=False, max_length=30, null=True
                    ),
                ),
                (
                    "billing_snapshot",
                    models.JSONField(blank=True, editable=False, null=True),
                ),
                (
                    "issuer_snapshot",
                    models.JSONField(blank=True, editable=False, null=True),
                ),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="transactions",
                        to="ERP.company",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="transactions",
                        to="ERP.customer",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="TransactionLineItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantity", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "unit_price_net",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                (
                    "vat_rate_percentage",
                    models.DecimalField(decimal_places=2, max_digits=5),
                ),
                ("total_net", models.DecimalField(decimal_places=2, max_digits=12)),
                ("total_vat", models.DecimalField(decimal_places=2, max_digits=12)),
                ("total_gross", models.DecimalField(decimal_places=2, max_digits=12)),
                ("product_name_snap", models.CharField(max_length=255)),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="ERP.product"
                    ),
                ),
                (
                    "transaction",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="line_items",
                        to="ERP.transaction",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Address",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("street", models.CharField(max_length=64)),
                ("number", models.CharField(max_length=12)),
                ("postal_code", models.CharField(max_length=20)),
                ("city", models.CharField(max_length=64)),
                (
                    "p_o",
                    models.CharField(blank=True, max_length=12, verbose_name="p.o box"),
                ),
                (
                    "country",
                    models.CharField(
                        choices=[
                            ("be", "Belgium"),
                            ("fr", "France"),
                            ("nl", "Netherlands"),
                            ("de", "Germany"),
                        ]
                    ),
                ),
                ("is_shipping", models.BooleanField(default=True)),
                ("is_billing", models.BooleanField(default=True)),
                ("is_shipping_default", models.BooleanField(default=False)),
                ("is_billing_default", models.BooleanField(default=False)),
                (
                    "partner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="addresses",
                        to="ERP.businesspartner",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("is_billing_default", True)),
                        fields=("partner",),
                        name="unique_default_billing_per_partner",
                    ),
                    models.UniqueConstraint(
                        condition=models.Q(("is_shipping_default", True)),
                        fields=("partner",),
                        name="unique_default_shipping_per_partner",
                    ),
                ],
            },
        ),
        migrations.AddConstraint(
            model_name="transaction",
            constraint=models.UniqueConstraint(
                fields=("company", "public_id"), name="unique_public_id_per_company"
            ),
        ),
    ]
