# Generated by Django 6.0 on 2026-05-30 12:29

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ERP", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="transaction",
            name="unique_public_id_per_company",
        ),
        migrations.RenameField(
            model_name="businesspartner",
            old_name="company",
            new_name="tenant",
        ),
        migrations.RenameField(
            model_name="product",
            old_name="company",
            new_name="tenant",
        ),
        migrations.RenameField(
            model_name="transaction",
            old_name="company",
            new_name="tenant",
        ),
        migrations.AddConstraint(
            model_name="transaction",
            constraint=models.UniqueConstraint(
                fields=("tenant", "public_id"), name="unique_public_id_per_tenant"
            ),
        ),
    ]
