# Generated by Django 6.0 on 2026-03-18 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ERP", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="transactionlineitem",
            name="vat_rate_percentage",
            field=models.DecimalField(decimal_places=2, default=6, max_digits=5),
            preserve_default=False,
        ),
    ]
