# Generated by Django 6.0 on 2026-06-01 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ERP", "0002_remove_transaction_unique_public_id_per_company_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="company",
            name="country",
            field=models.CharField(
                blank=True,
                choices=[
                    ("be", "Belgium"),
                    ("fr", "France"),
                    ("nl", "Netherlands"),
                    ("de", "Germany"),
                ],
            ),
        ),
    ]
