# Generated by Django 5.2.5 on 2025-09-24 13:05

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ERP", "0002_transaction_creation_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="customer",
            name="role",
            field=models.CharField(
                choices=[("client", "Client"), ("supplier", "Supplier")],
                default=django.utils.timezone.now,
                max_length=12,
            ),
            preserve_default=False,
        ),
    ]
