# Generated by Django 6.0 on 2026-04-15 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ERP", "0002_transactionlineitem_vat_rate_percentage"),
    ]

    operations = [
        migrations.AddField(
            model_name="address",
            name="is_billing_default",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="address",
            name="is_shipping_default",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="product",
            name="unit_measure",
            field=models.CharField(
                choices=[
                    ("kg", "Kg"),
                    ("l", "L"),
                    ("t", "Ton"),
                    ("u", "Unit"),
                    ("h", "Hour"),
                    ("a", "Are"),
                    ("ha", "Hectare"),
                ],
                max_length=3,
            ),
        ),
        migrations.AddConstraint(
            model_name="address",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_billing_default", True)),
                fields=("partner",),
                name="unique_default_billing_per_partner",
            ),
        ),
    ]
