# Generated by Django 6.0 on 2026-04-16 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ERP", "0003_address_is_billing_default_and_more"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="address",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_shipping_default", True)),
                fields=("partner",),
                name="unique_default_shipping_per_partner",
            ),
        ),
    ]
