# Generated by Django 6.0 on 2026-06-02 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ERP", "0003_alter_company_country"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="vat_rate",
            field=models.IntegerField(blank=True, default=6, max_length=3),
            preserve_default=False,
        ),
    ]
