# Generated by Django 6.0 on 2026-05-05 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ERP", "0004_address_unique_default_shipping_per_partner"),
    ]

    operations = [
        migrations.AddField(
            model_name="transaction",
            name="billing_snapshot",
            field=models.JSONField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name="transaction",
            name="local_sequence",
            field=models.PositiveIntegerField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name="transaction",
            name="public_id",
            field=models.CharField(
                blank=True, editable=False, max_length=30, null=True, unique=True
            ),
        ),
    ]
