# Generated by Django 6.0 on 2026-06-03 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ERP", "0004_product_vat_rate"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="description",
            field=models.TextField(blank=True, max_length=250),
        ),
        migrations.AlterField(
            model_name="product",
            name="type",
            field=models.CharField(
                blank=True,
                choices=[("o", "Object"), ("s", "Service")],
                default="o",
                max_length=3,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="unit_measure",
            field=models.CharField(
                blank=True,
                choices=[
                    ("kg", "Kg"),
                    ("l", "L"),
                    ("t", "Ton"),
                    ("u", "Unit"),
                    ("h", "Hour"),
                    ("a", "Are"),
                    ("ha", "Hectare"),
                ],
                max_length=3,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="unit_price",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="vat_rate",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
