# Generated by Django 5.2.5 on 2025-11-10 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ERP", "0004_customer_owner_alter_customer_email"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customer",
            name="phone",
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name="customer",
            name="role",
            field=models.CharField(
                choices=[("client", "Client"), ("supplier", "Supplier")], max_length=30
            ),
        ),
    ]
