# Generated by Django 6.0 on 2026-06-13 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ERP", "0005_alter_product_description_alter_product_type_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="customer",
            name="last_peppol_check",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="customer",
            name="peppol_status",
            field=models.CharField(
                choices=[
                    ("UN", "Not Verified"),
                    ("ACT", "Available"),
                    ("IN", "Not Found"),
                ],
                default="UN",
                max_length=20,
            ),
        ),
    ]
