# Generated by Django 6.0 on 2026-05-05 18:47

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ERP", "0005_transaction_billing_snapshot_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="transaction",
            name="public_id",
            field=models.CharField(
                blank=True, editable=False, max_length=30, null=True
            ),
        ),
        migrations.AddConstraint(
            model_name="transaction",
            constraint=models.UniqueConstraint(
                fields=("owner", "public_id"), name="unique_public_id_per_owner"
            ),
        ),
    ]
