# Generated by Django 6.0 on 2026-05-19 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ERP", "0006_alter_transaction_public_id_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="transactionlineitem",
            name="product_name_snap",
            field=models.CharField(default="x", max_length=255),
            preserve_default=False,
        ),
    ]
