# Generated by Django 6.0 on 2026-06-16 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ERP", "0006_customer_last_peppol_check_customer_peppol_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="company",
            name="legal_form",
            field=models.CharField(
                blank=True,
                choices=[
                    ("IN", "Entreprise Individuelle"),
                    ("SRL", "Société à Responsabilité limitée"),
                    ("SCN", "Société en Nom Collectif"),
                    ("SC", "Société Coopérative"),
                ],
                default="IN",
                max_length=64,
                null=True,
            ),
        ),
    ]
