# Generated by Django 5.2.5 on 2025-11-11 14:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ERP", "0003_customer_owner_customer_role_alter_customer_email_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="customer",
            old_name="name",
            new_name="first_name",
        ),
        migrations.RemoveField(
            model_name="transaction",
            name="amount",
        ),
        migrations.RemoveField(
            model_name="transaction",
            name="product",
        ),
        migrations.RemoveField(
            model_name="transaction",
            name="quantity",
        ),
        migrations.AddField(
            model_name="customer",
            name="last_name",
            field=models.CharField(default="", max_length=64),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="product",
            name="unit_measure",
            field=models.CharField(
                choices=[("kg", "Kg"), ("l", "L"), ("t", "Ton"), ("u", "Unit")],
                default=1,
                max_length=3,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="transaction",
            name="status",
            field=models.CharField(
                choices=[
                    ("new", "New"),
                    ("progress", "In Progress"),
                    ("cancelled", "Cancelled"),
                    ("completed", "Completed"),
                ],
                default=1,
                max_length=20,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="transaction",
            name="total_amount",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="unit_price",
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.CreateModel(
            name="TransactionLineItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantity", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "unit_price_at_sale",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                (
                    "line_total",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="ERP.product"
                    ),
                ),
                (
                    "transaction",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="line_items",
                        to="ERP.transaction",
                    ),
                ),
            ],
            options={
                "unique_together": {("transaction", "product")},
            },
        ),
    ]
