# Generated by Django 5.2.5 on 2025-11-17 13:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ERP", "0005_product_owner_transaction_owner"),
    ]

    operations = [
        migrations.CreateModel(
            name="Address",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("street", models.CharField(max_length=64)),
                ("number", models.CharField(max_length=12)),
                (
                    "p_o",
                    models.CharField(blank=True, max_length=12, verbose_name="p.o box"),
                ),
                ("city", models.CharField(max_length=64)),
                ("postal_code", models.IntegerField(max_length=12)),
                (
                    "country",
                    models.CharField(
                        choices=[
                            ("be", "Belgium"),
                            ("fr", "France"),
                            ("nl", "Netherlands"),
                            ("De", "Germany"),
                        ]
                    ),
                ),
            ],
        ),
        migrations.AlterField(
            model_name="customer",
            name="address",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="ERP.address"
            ),
        ),
    ]
