# Generated by Django 5.2.5 on 2025-11-17 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ERP", "0006_address_alter_customer_address"),
    ]

    operations = [
        migrations.AlterField(
            model_name="address",
            name="p_o",
            field=models.CharField(
                blank=True, max_length=12, null=True, verbose_name="p.o box"
            ),
        ),
    ]
