# Generated by Django 5.2.5 on 2025-11-17 14:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ERP", "0007_alter_address_p_o"),
    ]

    operations = [
        migrations.AlterField(
            model_name="address",
            name="p_o",
            field=models.CharField(
                blank=True, default=1, max_length=12, verbose_name="p.o box"
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="customer",
            name="address",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.CASCADE, to="ERP.address"
            ),
        ),
    ]
