# Generated by Django 5.2.5 on 2025-11-17 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ERP", "0008_alter_address_p_o_alter_customer_address"),
    ]

    operations = [
        migrations.AlterField(
            model_name="address",
            name="country",
            field=models.CharField(
                choices=[
                    ("be", "Belgium"),
                    ("fr", "France"),
                    ("nl", "Netherlands"),
                    ("de", "Germany"),
                ]
            ),
        ),
        migrations.AlterField(
            model_name="address",
            name="postal_code",
            field=models.IntegerField(),
        ),
    ]
