# Generated by Django 6.0 on 2025-12-16 15:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ERP", "0009_alter_address_country_alter_address_postal_code"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="customer",
            name="address",
        ),
        migrations.RemoveField(
            model_name="customer",
            name="email",
        ),
        migrations.RemoveField(
            model_name="customer",
            name="first_name",
        ),
        migrations.RemoveField(
            model_name="customer",
            name="id",
        ),
        migrations.RemoveField(
            model_name="customer",
            name="last_name",
        ),
        migrations.RemoveField(
            model_name="customer",
            name="owner",
        ),
        migrations.RemoveField(
            model_name="customer",
            name="phone",
        ),
        migrations.RemoveField(
            model_name="customer",
            name="role",
        ),
        migrations.AddField(
            model_name="address",
            name="is_billing",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="address",
            name="is_shipping",
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name="address",
            name="postal_code",
            field=models.CharField(max_length=20),
        ),
        migrations.CreateModel(
            name="BusinessPartner",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("firstname", models.CharField(blank=True, max_length=64)),
                ("email", models.EmailField(blank=True, max_length=255)),
                ("phone", models.CharField(blank=True, max_length=30)),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("CUS", "Customer"),
                            ("SUP", "Supplier"),
                            ("CON", "Contact"),
                            ("GEN", "General"),
                        ],
                        max_length=3,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="address",
            name="partner",
            field=models.ForeignKey(
                default=0,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="addresses",
                to="ERP.businesspartner",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="customer",
            name="businesspartner_ptr",
            field=models.OneToOneField(
                auto_created=True,
                default=0,
                on_delete=django.db.models.deletion.CASCADE,
                parent_link=True,
                primary_key=True,
                serialize=False,
                to="ERP.businesspartner",
            ),
            preserve_default=False,
        ),
    ]
