from django import forms
from django.contrib.auth.forms import AuthenticationForm, UserCreationForm
from django.forms import inlineformset_factory, BaseInlineFormSet
from ERP.models import Address, Company, Customer, Product, Transaction, TransactionLineItem
from .mixins import TailwindFormMixin

class LoginForm(TailwindFormMixin, AuthenticationForm):
    pass

class RegistrationForm(TailwindFormMixin, UserCreationForm):
    pass

class CreateCompanyForm(TailwindFormMixin, forms.ModelForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields["vat_number"].widget.attrs.update({"placeholder": "Ex: BE 123.456.789"})
    class Meta:
        model = Company
        exclude = ['users']

class CreateCustomerForm(TailwindFormMixin, forms.ModelForm):
    """
    This form will automatically have Tailwind styling on all fields 
    because it inherits from TailwindFormMixin.
    """
    class Meta:
        model = Customer
        fields = ('title', 'name', 'first_name', 'phone', 'email', 'vat_number')
        widgets = {
            'email': forms.EmailInput(attrs={'type': 'email'}),
            'phone_number': forms.TextInput(attrs={'type': 'tel'}),
        }

class CreateAddressForm(TailwindFormMixin, forms.ModelForm):
     class Meta:
          model = Address
          exclude = ['partner']

class CreateProductForm(TailwindFormMixin, forms.ModelForm):
     class Meta:
          model = Product
          fields = ('name', 'description', 'unit_measure', 'unit_price', 'type', 'vat_rate')

# Define the form for the individual line item (used by the formset)
class TransactionLineItemForm(TailwindFormMixin, forms.ModelForm):
    total_gross = forms.DecimalField(required=False)
    
    def __init__(self, *args, **kwargs):
        tenant = kwargs.pop('tenant', None)
        super().__init__(*args, **kwargs)
        if tenant:
            self.fields['product'].queryset = Product.objects.filter(tenant=tenant)
    
    class Meta:
        model = TransactionLineItem
        fields = ['product', 'quantity', 'unit_price_net','vat_rate_percentage','total_gross'] 

# 1. On crée une classe qui hérite du comportement de base
class BaseTransactionLineItemFormSet(BaseInlineFormSet):
    def validate_unique(self):
        # En ne faisant rien ici, on désactive la vérification des doublons
        return 

# 2. On passe cette classe à la factory via l'argument 'formset'
# Create the Formset Factory
# We link the Parent model (Transaction) to the Child model (TransactionLineItem)
TransactionLineItemFormSet = inlineformset_factory(
    Transaction, 
    TransactionLineItem,
    form=TransactionLineItemForm, # Ton formulaire de ligne
    formset=BaseTransactionLineItemFormSet, # <--- C'est ici qu'on branche la logique
    extra=1,
    can_delete=True
)

class CreateTransactionForm(TailwindFormMixin, forms.ModelForm):
    class Meta:
        model = Transaction
        fields = ['customer','type']
        
    def __init__(self, *args, **kwargs):
        # 1. Extract the tenant passed from the view
        tenant = kwargs.pop('tenant', None) 
        # 2. Initialize the form normally
        super().__init__(*args, **kwargs)
        # 3. Filter the 'customer' field generated by Meta
        if tenant:
            self.fields['customer'].queryset = Customer.objects.filter(tenant=tenant)
    
    def clean_status(self):
        """Sécurité optionnelle : au cas où un malin injecte 'status' dans la requête POST"""
        return 'new'